# Generated by Django 4.2.14 on 2024-07-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_collections', '0004_remove_collection_target_group'),
        ('users', '0003_group_user_collection_manager_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
