# Generated by Django 4.2.14 on 2024-07-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_collections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection_target',
            name='name',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
