# Generated by Django 4.2.14 on 2024-07-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_collections', '0003_collection_target_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection_target',
            name='group',
        ),
    ]
