# Generated by Django 4.2.14 on 2024-07-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_collections', '0004_remove_collection_target_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_point',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
