# Generated by Django 4.2.14 on 2024-07-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_collections', '0005_collection_collection_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection_target',
            name='collected',
            field=models.BooleanField(default=False),
        ),
    ]
