# Generated by Django 4.2.14 on 2024-07-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_collections', '0008_alter_collection_target_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection_target',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
