# Generated by Django 4.2.14 on 2024-07-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_collections', '0009_alter_collection_target_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection_target',
            name='host_url',
            field=models.URLField(default='google.com'),
            preserve_default=False,
        ),
    ]
